### ISSUE TITLE
Can u help me

### ISSUE THREAD

**Issue by aarvndhNG** [ATFGK/HitMonsterHPPromptForTShock#2]
Can u update a mini game plugin @ATFGK

**Comment by ATFGK** [comment]
Which one？





------------------ Original ------------------
From: That Blackwolf ***@***.***&gt;
Date: Thu,Mar 16,2023 0:35 PM
To: ATFGK/HitMonsterHPPromptForTShock ***@***.***&gt;
Cc: ATFGK ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ATFGK/HitMonsterHPPromptForTShock] Can u help me (Issue #2)





 
Can u update a mini game plugin @ATFGK

**Comment by aarvndhNG** [comment]
https://www.bbstr.net/t/1712/

I need a English version of this plugin if u want i have English resource but i can't build it

**Comment by ATFGK** [comment]
No, because I'm not the author of the plugin.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ATFGK/HitMonsterHPPromptForTShock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ATFGK/HitMonsterHPPromptForTShock] Can u help me (Issue #2)





 
https://www.bbstr.net/t/1712/
 
I need a English version of this plugin if u want i have English resource but i can't build it

**Comment by aarvndhNG** [comment]
> No, because I'm not the author of the plugin.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ATFGK/HitMonsterHPPromptForTShock" ***@***.***&gt;; 发送时间:&nbsp;2023年3月16日(星期四) 晚上9:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ATFGK/HitMonsterHPPromptForTShock] Can u help me (Issue #2) https://www.bbstr.net/t/1712/ I need a English version of this plugin if u want i have English resource but i can't build it — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

I  ask the author and he said i am busy so you update

**Comment by ATFGK** [comment]
sorry，I‘m busy，too.....



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "That ***@***.***&gt;; 
发送时间: 2023年3月18日(星期六) 晚上6:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ATFGK/HitMonsterHPPromptForTShock] Can u help me (Issue #2)





  
No, because I'm not the author of the plugin.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ATFGK/HitMonsterHPPromptForTShock" @.&gt;; 发送时间:&nbsp;2023年3月16日(星期四) 晚上9:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ATFGK/HitMonsterHPPromptForTShock] Can u help me (Issue #2) https://www.bbstr.net/t/1712/ I need a English version of this plugin if u want i have English resource but i can't build it — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
I  ask the author and he said i am busy so you update

**Comment by aarvndhNG** [comment]
Did you remember me

**Comment by ATFGK** [comment]
No




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ATFGK/HitMonsterHPPromptForTShock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月19日(星期天) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ATFGK/HitMonsterHPPromptForTShock] Can u help me (Issue #2)





 
Did you remember me

**Comment by aarvndhNG** [comment]
I updated to English version one of your plugin now do you remember that guy

**Comment by aarvndhNG** [comment]
@ATFGK
